obstacle_range: 2.5
raytrace_range: 3.0

# ROBOT FOOTPRINT
# Define the corners of your rover (in meters) relative to center.
# Example for a 50cm x 40cm rover:
footprint: [[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]
# inflation_radius: Keep obstacles at least this far away
inflation_radius: 0.55

# SENSORS
observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# Use Kinect PointCloud to detect obstacles the Lidar misses (like rocks low to ground)
point_cloud_sensor: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true, min_obstacle_height: 0.05}
